services:
  db:
    image: postgres:16-alpine
    container_name: medium75-db
    environment:
      POSTGRES_DB: medium75
      POSTGRES_USER: medium75
      POSTGRES_PASSWORD: medium75
    ports:
      - "5432:5432"
    volumes:
      - medium75-db-data:/var/lib/postgresql/data

volumes:
  medium75-db-data:
